import { useState, useEffect } from "react";
import { supabase } from "../supabase";

export function meta() {
  return [
    { title: "Supabase Auth Testing" },
    { name: "description", content: "Testing Supabase Authentication" },
  ];
}

export default function SupabaseTest() {
  const [connectionStatus, setConnectionStatus] = useState("Checking...");
  const [signUpEmail, setSignUpEmail] = useState("");
  const [signUpUsername, setSignUpUsername] = useState("");
  const [signUpPassword, setSignUpPassword] = useState("");
  const [signInEmail, setSignInEmail] = useState("");
  const [signInPassword, setSignInPassword] = useState("");
  const [currentUser, setCurrentUser] = useState(null);
  const [loading, setLoading] = useState(false);

  // Test Supabase connection and check for logged-in user
  useEffect(() => {
    testConnection();
    checkUser();
  }, []);

  const testConnection = async () => {
    try {
      const { data, error } = await supabase.auth.getSession();
      setConnectionStatus("✅ Connected to Supabase Auth!");
    } catch (error) {
      console.error("Supabase connection error:", error);
      setConnectionStatus(`❌ Connection failed: ${error.message}`);
    }
  };

  const checkUser = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    setCurrentUser(user);
  };

  const handleSignUp = async (e) => {
    e.preventDefault();
    if (!signUpEmail.trim() || !signUpUsername.trim() || !signUpPassword.trim()) {
      alert("Please enter email, username, and password");
      return;
    }

    setLoading(true);
    try {
      // Sign up with auth and set fname/lname in user metadata
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: signUpEmail,
        password: signUpPassword,
        options: {
          data: {
            fname: signUpUsername,
            lname: '',
          },
        },
      });

      if (authError) throw authError;

      // If user was created, sync to custom users table
      if (authData.user) {
        const { error: dbError } = await supabase
          .from('users')
          .insert([{
            id: authData.user.id,  // UID from auth (must be UUID type in your table!)
            fname: signUpUsername,  // First name
            lname: '',  // Last name
            email: signUpEmail,  // Email
            created_at: authData.user.created_at,  // Created at from auth
            last_sign_in: authData.user.last_sign_in_at || new Date().toISOString(),  // Last sign in
            // created_at_pst is auto-generated by database
          }]);

        if (dbError) {
          console.error("Error syncing to users table:", dbError);
          alert(`⚠️ Auth user created, but failed to sync to custom users table: ${dbError.message}\n\nMake sure your 'users' table has 'id' as UUID type, not int8!`);
        } else {
          console.log("✅ Successfully synced to custom users table");
        }
      }

      alert("Sign up successful! User stored in Supabase Auth and custom users table.");
      setSignUpEmail("");
      setSignUpUsername("");
      setSignUpPassword("");
      checkUser();
    } catch (error) {
      console.error("Error signing up:", error);
      alert(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleSignIn = async (e) => {
    e.preventDefault();
    if (!signInEmail.trim() || !signInPassword.trim()) {
      alert("Please enter both email and password");
      return;
    }

    setLoading(true);
    try {
      const { data, error } = await supabase.auth.signInWithPassword({
        email: signInEmail,
        password: signInPassword,
      });

      if (error) throw error;

      // Update last_sign_in in custom users table
      if (data.user) {
        await supabase
          .from('users')
          .update({ last_sign_in: data.user.last_sign_in_at || new Date().toISOString() })
          .eq('id', data.user.id);
      }

      alert("Sign in successful!");
      setSignInEmail("");
      setSignInPassword("");
      checkUser();
    } catch (error) {
      console.error("Error signing in:", error);
      alert(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleSignOut = async () => {
    try {
      const { error } = await supabase.auth.signOut();
      if (error) throw error;

      alert("Signed out successfully!");
      setCurrentUser(null);
    } catch (error) {
      console.error("Error signing out:", error);
      alert(`Error: ${error.message}`);
    }
  };

  return (
    <div style={{ padding: "40px", maxWidth: "800px", margin: "0 auto", fontFamily: "system-ui, sans-serif", color: "#000000" }}>
      <h1 style={{ fontSize: "2.5rem", marginBottom: "20px", color: "#000000" }}>Supabase Auth Test</h1>

      {/* Connection Status */}
      <div style={{
        padding: "20px",
        backgroundColor: connectionStatus.includes("✅") ? "#d4edda" : "#f8d7da",
        border: "1px solid",
        borderColor: connectionStatus.includes("✅") ? "#c3e6cb" : "#f5c6cb",
        borderRadius: "8px",
        marginBottom: "30px",
        color: "#000000"
      }}>
        <h2 style={{ margin: "0 0 10px 0", color: "#000000" }}>Connection Status</h2>
        <p style={{ margin: 0, fontSize: "1.1rem", color: "#000000" }}>{connectionStatus}</p>
      </div>

      {/* Current User Status */}
      <div style={{
        padding: "20px",
        backgroundColor: currentUser ? "#d1ecf1" : "#f8f9fa",
        border: "1px solid",
        borderColor: currentUser ? "#bee5eb" : "#dee2e6",
        borderRadius: "8px",
        marginBottom: "30px",
        color: "#000000"
      }}>
        <h2 style={{ margin: "0 0 10px 0", color: "#000000" }}>Current User</h2>
        {currentUser ? (
          <div>
            <p style={{ margin: "0 0 10px 0", color: "#000000" }}>
              <strong>Username:</strong> {currentUser.user_metadata?.fname && currentUser.user_metadata?.lname ? `${currentUser.user_metadata.fname} ${currentUser.user_metadata.lname}` : currentUser.user_metadata?.fname || "Not set"}
            </p>
            <p style={{ margin: "0 0 10px 0", color: "#000000" }}>
              <strong>Email:</strong> {currentUser.email}
            </p>
            <p style={{ margin: "0 0 10px 0", color: "#000000" }}>
              <strong>User ID:</strong> {currentUser.id}
            </p>
            <p style={{ margin: "0 0 10px 0", fontSize: "0.9rem", color: "#6c757d" }}>
              Created: {new Date(currentUser.created_at).toLocaleString()}
            </p>
            <p style={{ margin: "0 0 15px 0", fontSize: "0.9rem", color: "#6c757d" }}>
              Last Sign In: {currentUser.last_sign_in_at ? new Date(currentUser.last_sign_in_at).toLocaleString() : "N/A"}
            </p>
            <button
              onClick={handleSignOut}
              style={{
                padding: "8px 16px",
                fontSize: "0.9rem",
                backgroundColor: "#dc3545",
                color: "white",
                border: "none",
                borderRadius: "4px",
                cursor: "pointer"
              }}
            >
              Sign Out
            </button>
          </div>
        ) : (
          <p style={{ margin: 0, color: "#6c757d" }}>Not logged in</p>
        )}
      </div>

      {/* Sign Up Form */}
      <div style={{
        padding: "20px",
        backgroundColor: "#f8f9fa",
        border: "1px solid #dee2e6",
        borderRadius: "8px",
        marginBottom: "20px",
        color: "#000000"
      }}>
        <h2 style={{ marginTop: 0, color: "#000000" }}>Sign Up (Register New User)</h2>
        <form onSubmit={handleSignUp}>
          <input
            type="email"
            value={signUpEmail}
            onChange={(e) => setSignUpEmail(e.target.value)}
            placeholder="Enter email..."
            style={{
              width: "100%",
              padding: "12px",
              fontSize: "1rem",
              border: "1px solid #ced4da",
              borderRadius: "4px",
              marginBottom: "10px",
              boxSizing: "border-box",
              color: "#000000"
            }}
          />
          <input
            type="text"
            value={signUpUsername}
            onChange={(e) => setSignUpUsername(e.target.value)}
            placeholder="Enter username (display name)..."
            style={{
              width: "100%",
              padding: "12px",
              fontSize: "1rem",
              border: "1px solid #ced4da",
              borderRadius: "4px",
              marginBottom: "10px",
              boxSizing: "border-box",
              color: "#000000"
            }}
          />
          <input
            type="password"
            value={signUpPassword}
            onChange={(e) => setSignUpPassword(e.target.value)}
            placeholder="Enter password (min 6 characters)..."
            style={{
              width: "100%",
              padding: "12px",
              fontSize: "1rem",
              border: "1px solid #ced4da",
              borderRadius: "4px",
              marginBottom: "10px",
              boxSizing: "border-box",
              color: "#000000"
            }}
          />
          <button
            type="submit"
            disabled={loading}
            style={{
              padding: "12px 24px",
              fontSize: "1rem",
              backgroundColor: loading ? "#6c757d" : "#28a745",
              color: "white",
              border: "none",
              borderRadius: "4px",
              cursor: loading ? "not-allowed" : "pointer",
              marginRight: "10px"
            }}
          >
            {loading ? "Processing..." : "Sign Up"}
          </button>
        </form>
      </div>

      {/* Sign In Form */}
      <div style={{
        padding: "20px",
        backgroundColor: "#ffffff",
        border: "1px solid #dee2e6",
        borderRadius: "8px",
        color: "#000000"
      }}>
        <h2 style={{ marginTop: 0, color: "#000000" }}>Sign In (Login)</h2>
        <form onSubmit={handleSignIn}>
          <input
            type="email"
            value={signInEmail}
            onChange={(e) => setSignInEmail(e.target.value)}
            placeholder="Enter email..."
            style={{
              width: "100%",
              padding: "12px",
              fontSize: "1rem",
              border: "1px solid #ced4da",
              borderRadius: "4px",
              marginBottom: "10px",
              boxSizing: "border-box",
              color: "#000000"
            }}
          />
          <input
            type="password"
            value={signInPassword}
            onChange={(e) => setSignInPassword(e.target.value)}
            placeholder="Enter password..."
            style={{
              width: "100%",
              padding: "12px",
              fontSize: "1rem",
              border: "1px solid #ced4da",
              borderRadius: "4px",
              marginBottom: "10px",
              boxSizing: "border-box",
              color: "#000000"
            }}
          />
          <button
            type="submit"
            disabled={loading}
            style={{
              padding: "12px 24px",
              fontSize: "1rem",
              backgroundColor: loading ? "#6c757d" : "#007bff",
              color: "white",
              border: "none",
              borderRadius: "4px",
              cursor: loading ? "not-allowed" : "pointer"
            }}
          >
            {loading ? "Processing..." : "Sign In"}
          </button>
        </form>

        <div style={{
          marginTop: "20px",
          padding: "15px",
          backgroundColor: "#fff3cd",
          border: "1px solid #ffc107",
          borderRadius: "4px",
          color: "#000000"
        }}>
          <strong>🔒 Secure:</strong> Passwords are automatically hashed by Supabase Auth. They are never stored in plain text!
        </div>
      </div>
    </div>
  );
}
