create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    fname text,
    lname text,
    email text,
    image_url text,
    role text not null default 'user'
);

create table if not exists public.webinars (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    title text not null,
    webinar_url text not null,
    date date not null default current_date,
    webinar_thumbnail text,
    webinar_description text,
    speaker text not null,
    speaker_university text,
    speaker_image text,
    speaker_details text
);

alter table public.webinars add column if not exists created_at timestamptz default now();
alter table public.webinars add column if not exists updated_at timestamptz default now();
alter table public.webinars add column if not exists title text;
alter table public.webinars add column if not exists webinar_url text;
alter table public.webinars add column if not exists date date;
alter table public.webinars add column if not exists webinar_thumbnail text;
alter table public.webinars add column if not exists webinar_description text;
alter table public.webinars add column if not exists speaker text;
alter table public.webinars add column if not exists speaker_university text;
alter table public.webinars add column if not exists speaker_image text;
alter table public.webinars add column if not exists speaker_details text;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
        and table_name = 'webinars'
        and column_name = 'primary_video'
    ) then
        execute 'update public.webinars set webinar_url = coalesce(webinar_url, primary_video) where webinar_url is null';
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
        and table_name = 'webinars'
        and column_name = 'thumbnail'
    ) then
        execute 'update public.webinars set webinar_thumbnail = coalesce(webinar_thumbnail, thumbnail) where webinar_thumbnail is null';
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
        and table_name = 'webinars'
        and column_name = 'subtitle'
    ) then
        execute 'update public.webinars set webinar_description = coalesce(webinar_description, subtitle) where webinar_description is null';
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
        and table_name = 'webinars'
        and column_name = 'date_text'
    ) then
        execute $backfill_dates$
            update public.webinars
            set date = case
                when date_text ~ '^\d{4}/\d{2}/\d{2}$' then to_date(date_text, 'YYYY/MM/DD')
                when date_text ~ '^\d{4}-\d{2}-\d{2}$' then date_text::date
                when date_text ~ '^\d{1,2}/\d{1,2}/\d{4}$' then to_date(date_text, 'MM/DD/YYYY')
                else null
            end
            where date is null
        $backfill_dates$;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
        and table_name = 'webinars'
        and column_name = 'speakers'
    ) then
        execute $backfill_speakers$
            update public.webinars
            set
                speaker = coalesce(
                    speaker,
                    case
                        when jsonb_typeof(speakers) = 'array' then speakers->0->>'name'
                        when jsonb_typeof(speakers) = 'object' then speakers->>'name'
                        else null
                    end
                ),
                speaker_university = coalesce(
                    speaker_university,
                    case
                        when jsonb_typeof(speakers) = 'array' then coalesce(speakers->0->>'university', speakers->0->>'institution', speakers->0->>'affiliation')
                        when jsonb_typeof(speakers) = 'object' then coalesce(speakers->>'university', speakers->>'institution', speakers->>'affiliation')
                        else null
                    end
                ),
                speaker_image = coalesce(
                    speaker_image,
                    case
                        when jsonb_typeof(speakers) = 'array' then coalesce(speakers->0->>'image', speakers->0->>'image_url')
                        when jsonb_typeof(speakers) = 'object' then coalesce(speakers->>'image', speakers->>'image_url')
                        else null
                    end
                ),
                speaker_details = coalesce(
                    speaker_details,
                    case
                        when jsonb_typeof(speakers) = 'array' then coalesce(speakers->0->>'details', speakers->0->>'description', speakers->0->>'bio')
                        when jsonb_typeof(speakers) = 'object' then coalesce(speakers->>'details', speakers->>'description', speakers->>'bio')
                        else null
                    end
                )
            where speakers is not null
        $backfill_speakers$;
    end if;
end $$;

update public.webinars
set date = current_date
where date is null;

alter table public.webinars alter column date set default current_date;

create or replace function public.set_webinars_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_webinars_updated_at on public.webinars;
create trigger set_webinars_updated_at
before update on public.webinars
for each row
execute function public.set_webinars_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.users
        where id = auth.uid()
        and role = 'admin'
    );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.webinars enable row level security;

drop policy if exists "Public can read webinars" on public.webinars;
create policy "Public can read webinars"
on public.webinars
for select
using (true);

drop policy if exists "Admins can insert webinars" on public.webinars;
create policy "Admins can insert webinars"
on public.webinars
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update webinars" on public.webinars;
create policy "Admins can update webinars"
on public.webinars
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete webinars" on public.webinars;
create policy "Admins can delete webinars"
on public.webinars
for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('webinars', 'webinars', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read webinar files" on storage.objects;
create policy "Public can read webinar files"
on storage.objects
for select
using (bucket_id = 'webinars');

drop policy if exists "Admins can upload webinar files" on storage.objects;
create policy "Admins can upload webinar files"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'webinars' and public.is_admin());

drop policy if exists "Admins can update webinar files" on storage.objects;
create policy "Admins can update webinar files"
on storage.objects
for update
to authenticated
using (bucket_id = 'webinars' and public.is_admin())
with check (bucket_id = 'webinars' and public.is_admin());

drop policy if exists "Admins can delete webinar files" on storage.objects;
create policy "Admins can delete webinar files"
on storage.objects
for delete
to authenticated
using (bucket_id = 'webinars' and public.is_admin());
